amerdale/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', namespace='webapp'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'

urlpatterns = [
    path('', views.landing_page, name='home'),
    path('register', views.create_user, name='register'),
]

webapp/models.py
from django.db import models

# Create your models here.

webapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
import django.db

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = [
            'username',
            'password1',
            'password2'
        ]

webapp/views.py
from django.shortcuts import redirect, render
from . import forms

# Create your views here.
def landing_page(request):
    return render(request, 'webapp/index.html')

def create_user(request):
    form = forms.CreateUserForm()

    if request.method == 'POST':
        form = forms.CreateUserForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('webapp:home')
    
    context = {
        'form': form
    }

    return render(request, "webapp/registration.html", context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Amerdale</title>
    <link rel="stylesheet" href="https://bootswatch.com/5/slate/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.min.js"
        integrity="sha384-+sLIOodYLS7CIrQpBjl+C7nPvqq+FbNUBDunl/OZv93DB7Ln/533i8e/mZXLi/P+"
        crossorigin="anonymous"></script>
</head>

<body>
    <!-- Navbar -->
    {% include "navbar.html" %}

    <div class="container">
        {% block content %}

        {% endblock content %}
    </div>
</body>
<link rel="stylesheet" href="{% static 'js/app.js' %}">

</html>

templates/navbar.html
<!-- Navbar -->

<nav class="navbar navbar-expand navbar-dark bg-primary justify-content-center">

    <a class="navbar-brand main-heading" href="{% url 'webapp:home' %}">

        &nbsp; HOME

    </a>


    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>

    </button>


    <div class="collapse navbar-collapse text-center" id="navbarNavDropdown">


        <ul class="navbar-nav mr-auto">


            &nbsp; &nbsp; &nbsp;

            {% if user.is_authenticated %}

            <li class="nav-item">

                <a class="nav-link" href="{% url 'webapp:home' %}">Dashboard &nbsp; <i class="fa fa-home"
                        aria-hidden="true"></i>
                </a>

            </li>


            &nbsp; &nbsp; &nbsp;


            <li class="nav-item">

                <a class="nav-link" href="{% url 'webapp:home' %}">Sign out &nbsp; <i class="fa fa-sign-out"
                        aria-hidden="true"></i> </a>

            </li>


        </ul>

        {% else %}

        <li class="nav-item">

            <a class="nav-link" href="{% url 'webapp:register' %}"> Register &nbsp; <i
                    class="fa-solid fa-user-plus"></i></a>

        </li>


        &nbsp; &nbsp; &nbsp;


        <li class="nav-item">

            <a class="nav-link" href="{% url 'webapp:home' %}">Login &nbsp; <i class="fa-solid fa-user"></i></a>

        </li>


        {% endif %}


    </div>


</nav>

templates/webapp/index.html
{% extends "base.html" %}

{% block content %}

{% load static %}

<div class="text-center p-5">
    <h1>Welcome to world of Amerdale</h1>
    <hr>
</div>
<div class="d-flex justify-content-around">
    <div class="card-img-container">
        <img src="{% static 'images/walkintotheshadow.webp' %}" class="card-img-top" alt="Left Image"
            style="width: 300px; height: 450px;">
    </div>
    <div class="card-img-container">
        <img src="{% static 'images/alone.webp' %}" class="card-img-top" alt="Main Image"
            style="width: 300px; height: 450px;">
    </div>
    <div class="card-img-container">
        <img src="{% static 'images/soul.jpg' %}" class="card-img-top" alt="Right Image"
            style="width: 300px; height: 450px;">
    </div>
</div>

{% endblock content %}

templates/webapp/registration.html
{% extends "base.html" %}

{% block content %}
<div class="container bg-light shadow-md p-5 form-layout">

    <h3>Create your account</h3>

    <h5> Start managing your clients today!</h5>

    <hr>
    <br>

    <form class="form-check" method="post">
        {% csrf_token %}

        {{form.as_p}}
        <button type="submit">Create an Account</button>
    </form>
</div>

{% endblock content %}